config/routes.rb
Rails.application.routes.draw do
  resources :breast_feedings
  resources :babies
  root "babies#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/baby.rb
class Baby < ApplicationRecord
    has_many :breast_feedings, dependent: :destroy

    def to_s
        name
    end 

    def total_drinking
        breast_feedings.sum(:quantity)
    end

    def total_duration
        breast_feedings.sum(:duration)
    end

    #Cantidad de veces que el bebé tomó hasta ahora
    def breast_feeding_times_today
        breast_feedings.where("created_at >= :start_at AND created_at <= :end_date", {start_at: Time.now.beginning_of_day, end_date: Time.now}).count 
    end

    #fecha de la ultima vez que bebió
    def last_time_drinking
        if breast_feedings.count > 0
            breast_feedings.last.created_at 
        else
            ''
        end
    end 

    #Por cuanto tiempo ha bebido hoy 
    def breast_feeding_duration_today 
        breast_feedings.where("created_at >= :start_at AND created_at <= :end_date", {start_at: Time.now.beginning_of_day, end_date: Time.now}).sum(:duration)
    end

    #Cuanta cantidad bebio hoy 
    def breast_feeding_quantity_today
        breast_feedings.where("created_at >= :start_at AND created_at <= :end_date", {start_at: Time.now.beginning_of_day, end_date: Time.now}).sum(:quantity)
    end


end

app/models/breast_feeding.rb
class BreastFeeding < ApplicationRecord
  belongs_to :baby
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/babies_controller.rb
class BabiesController < ApplicationController
  before_action :set_baby, only: [:show, :edit, :update, :destroy]

  # GET /babies
  # GET /babies.json
  def index
    @babies = Baby.all
  end

  # GET /babies/1
  # GET /babies/1.json
  def show
  end

  # GET /babies/new
  def new
    @baby = Baby.new
  end

  # GET /babies/1/edit
  def edit
  end

  # POST /babies
  # POST /babies.json
  def create
    @baby = Baby.new(baby_params)

    respond_to do |format|
      if @baby.save
        format.html { redirect_to @baby, notice: 'Baby was successfully created.' }
        format.json { render :show, status: :created, location: @baby }
      else
        format.html { render :new }
        format.json { render json: @baby.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /babies/1
  # PATCH/PUT /babies/1.json
  def update
    respond_to do |format|
      if @baby.update(baby_params)
        format.html { redirect_to @baby, notice: 'Baby was successfully updated.' }
        format.json { render :show, status: :ok, location: @baby }
      else
        format.html { render :edit }
        format.json { render json: @baby.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /babies/1
  # DELETE /babies/1.json
  def destroy
    @baby.destroy
    respond_to do |format|
      format.html { redirect_to babies_url, notice: 'Baby was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_baby
      @baby = Baby.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def baby_params
      params.require(:baby).permit(:name)
    end
end

app/controllers/breast_feedings_controller.rb
class BreastFeedingsController < ApplicationController
  before_action :set_breast_feeding, only: [:show, :edit, :update, :destroy]

  # GET /breast_feedings
  # GET /breast_feedings.json
  def index
    @breast_feedings = BreastFeeding.all
  end

  # GET /breast_feedings/1
  # GET /breast_feedings/1.json
  def show
  end

  # GET /breast_feedings/new
  def new
    @breast_feeding = BreastFeeding.new
    @babies = Baby.pluck :name, :id
  end

  # GET /breast_feedings/1/edit
  def edit
    @babies = Baby.pluck :name, :id
  end

  # POST /breast_feedings
  # POST /breast_feedings.json
  def create
    @breast_feeding = BreastFeeding.new(breast_feeding_params)

    respond_to do |format|
      if @breast_feeding.save
        format.html { redirect_to @breast_feeding, notice: 'Breast feeding was successfully created.' }
        format.json { render :show, status: :created, location: @breast_feeding }
      else
        format.html { render :new }
        format.json { render json: @breast_feeding.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /breast_feedings/1
  # PATCH/PUT /breast_feedings/1.json
  def update
    respond_to do |format|
      if @breast_feeding.update(breast_feeding_params)
        format.html { redirect_to @breast_feeding, notice: 'Breast feeding was successfully updated.' }
        format.json { render :show, status: :ok, location: @breast_feeding }
      else
        format.html { render :edit }
        format.json { render json: @breast_feeding.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /breast_feedings/1
  # DELETE /breast_feedings/1.json
  def destroy
    @breast_feeding.destroy
    respond_to do |format|
      format.html { redirect_to breast_feedings_url, notice: 'Breast feeding was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_breast_feeding
      @breast_feeding = BreastFeeding.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def breast_feeding_params
      params.require(:breast_feeding).permit(:quantity, :duration, :baby_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/babies_helper.rb
module BabiesHelper
end

app/helpers/breast_feedings_helper.rb
module BreastFeedingsHelper
end

app/views/babies/_form.html.erb
  <%= form_with(model: baby, local: true) do |form| %>
    <% if baby.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(baby.errors.count, "error") %> prohibited this baby from being saved:</h2>

        <ul>
        <% baby.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

<div class="container margenes-form-baby">
    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div><br>

    <div class="actions">
      <%= form.submit %>
    </div><br>
  <% end %>
</div>

app/views/babies/edit.html.erb
<h1>Editing Baby</h1>

<%= render 'form', baby: @baby %>

<div class="botones-margenes">
    <%= link_to 'Ver', @baby %> |
    <%= link_to 'Back', babies_path %>
</div>  

app/views/babies/index.html.erb
<p id="notice"><%= notice %></p>

  <table class="container margenes-tabla table table-hover text-center">
    <thead>
      <tr>
        <th class="letra-content pr-1">Nombre</th>
        <th class="letra-content pr-1">Total cantidad <br>bebida</th>
        <th class="letra-content pr-1">Total tiempo <br>bebido</th>
        <th colspan="3" class="letra-content pr-1"></th>
      </tr>
    </thead>
    
    <tbody>
      
      <% @babies.each do |baby| %>
        <tr>
          <td class="letra-content"><%= baby.name %></td>
          <td class="letra-content"><%= baby.total_drinking %></td>
          <td class="letra-content"><%= baby.total_duration %></td>
          <td class="letra-content"><%= link_to 'Ver', baby %></td>
          <td class="letra-content"><%= link_to 'Editar nombre', edit_baby_path(baby) %></td>
          <td class="letra-content"><%= link_to 'Eliminar bebé', baby, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

app/views/babies/new.html.erb
<h1>New Baby</h1>

<%= render 'form', baby: @baby %>

<%= link_to 'Back', babies_path, :class => "text-back-margin" %>

app/views/babies/show.html.erb
<div class="container margenes-show-baby">
  <p id="notice"><%= notice %></p>

  <div class="margenes-show2 text-left">
    <p class="tipografia2">
      <strong>Name:</strong>
      <%= @baby.name %>
    </p>

    <ul>
      <% @baby.breast_feedings.each do |bf|%>
        <li class="tipografia2"><span>Cantidad: <%= bf.quantity %>, Duración: <%= bf.duration %></span></li>
        <% end%>
    </ul>
  </div><br>

  <table class="container table table-hover margenes-tabla2">
      <thead>
        <tr>
        <th class="letra-content">Veces que ha <br>tomado hoy</th>
        <th class="letra-content">Fecha de la <br> última vez que <br>bebió</th>
        <th class="letra-content">Cuanto tiempo <br>ha tomado <br>hoy</th>
        <th class="letra-content">Cuanto ha <br>bebido hoy</th>
        </tr>
      </thead>

    <tbody>
      <td class="letra-content"><%= @baby.breast_feeding_times_today%></td>
      <td class="letra-content"><%= @baby.last_time_drinking%></td>
      <td class="letra-content"><%= @baby.breast_feeding_duration_today %></td>
      <td class="letra-content"><%= @baby.breast_feeding_quantity_today%></td>
    </tbody>

  </table><br><br>

    <%= link_to 'Editar nombre', edit_baby_path(@baby) %> |
    <%= link_to 'Back', babies_path %>
 
 </div> 

app/views/breast_feedings/_form.html.erb
<%= form_with(model: breast_feeding, local: true) do |form| %>
  <% if breast_feeding.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(breast_feeding.errors.count, "error") %> prohibited this breast_feeding from being saved:</h2>

      <ul>
      <% breast_feeding.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="container margenes-form-feedings">
    <div class="field">
      <%= form.label :quantity %>
      <%= form.text_field :quantity %>
    </div><br>

    <div class="field">
      <%= form.label :duration %>
      <%= form.text_field :duration %>
    </div><br>

    <div class="field">
      <%= form.label :baby_id %>
      <%= form.select :baby_id, options_for_select(@babies) %>
    </div><br>

    <div class="actions">
      <%= form.submit %>
    </div><br>
  </div>
<% end %>

app/views/breast_feedings/edit.html.erb
<h1>Editing Breast Feeding</h1>

<%= render 'form', breast_feeding: @breast_feeding %>

<%= link_to 'Show', @breast_feeding %> |
<%= link_to 'Back', breast_feedings_path %>

app/views/breast_feedings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Breast Feedings</h1>

<table class="container table table-hover margenes-tabla3">
  <thead>
    <tr>
      <th>Quantity</th>
      <th>Duration</th>
      <th>Baby</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @breast_feedings.each do |breast_feeding| %>
      <tr>
        <td><%= breast_feeding.quantity %></td>
        <td><%= breast_feeding.duration %></td>
        <td><%= breast_feeding.baby %></td>
        <td><%= link_to 'Show', breast_feeding %></td>
        <td><%= link_to 'Edit', edit_breast_feeding_path(breast_feeding) %></td>
        <td><%= link_to 'Destroy', breast_feeding, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nueva comida', new_breast_feeding_path %>

app/views/breast_feedings/new.html.erb
<h1>New Breast Feeding</h1>

<%= render 'form', breast_feeding: @breast_feeding %>

<%= link_to 'Back', breast_feedings_path, :class => "text-back-new-feedings" %>

app/views/breast_feedings/show.html.erb
<div class="margenes-show3 text-center">

  <p id="notice"><%= notice %></p>

  <p>
    <strong>Quantity:</strong>
    <%= @breast_feeding.quantity %>
  </p><br>

  <p>
    <strong>Duration:</strong>
    <%= @breast_feeding.duration %>
  </p><br>

  <p>
    <strong>Baby:</strong>
    <%= @breast_feeding.baby %>
  </p><br>

  <%= link_to 'Edit', edit_breast_feeding_path(@breast_feeding) %> |
  <%= link_to 'Back', breast_feedings_path %>

 </div> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Manjula</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css2?family=Rock+Salt&display=swap" rel="stylesheet">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>


  </head>


  <body class="fondo-simpsons">

  <!--Nav-->
    <nav class="navbar navbar-expand-lg color-bkg navbar-light tamaño-nav fixed-top">

      <%= image_tag("Pria.png", :class => "icono-pria")%>
      <a class="navbar-brand color-letras-nav">Bebés de Manjula y Apu</a>
      <%= image_tag("Anu.png", :class => "icono-anu")%>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      
      <div class="collapse navbar-collapse color-bkg" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item active pl-3">
            <%= link_to 'Bebés', babies_url, :class => "nav-link color-letras-nav"%>
          </li>
          <li class="nav-item pl-3">
            <%= link_to 'Nuevo bebé', new_baby_path, :class => "nav-link color-letras-nav"%>
          </li>
          <li class="nav-item pl-3">
            <%= link_to 'Nueva comida', new_breast_feeding_path, :class => "nav-link color-letras-nav"%>
          </li>
        </ul>
      </div>
    </nav>

  <!--Cuerpo de cada vista-->
    <div class = "container">
      <%= yield %>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </body>
</html>